### ISSUE TITLE
Illegal data address in read_input_bits

### ISSUE THREAD

**Issue by quenorha** [WAGO/pfc-modbus-server#1]
I get a Modbus exception from the server when I try to read digital inputs in read input bits (02) function code. 
I use address 0 like a standard Modbus coupler. 
I have just 750-430 & 750-530 modules.

Other FC work as expected. 

Logs :

 
  start init daemons
  dip-switch not found in /sys/devices/
  INFO: tty_rs232_485 is not available
  start kbus-modbus-server damon
  verbosity level is 7
  Not running in background
  kbusmodbusslave running...
  ADI Device[0]: libpackbus
  Found kbus device on: 0
  Modbus: Wait for KBUS to be initialized
  KBUS device open OK
  KBUS set to application state: 1
  
          .KbusBitCount: 32
          .TerminalCount: 2
          .ErrorCode: 0
          .ErrorArg: 0
          .ErrorPos: 0
          .BitCountAnalogInput: 0
          .BitCountAnalogOutput: 0
          .BitCountDigitalInput: 8
          .BitCountDigitalOutput: 8
  Offset: IN: 0 - OUT: 0
  
   Pos:1:  Type: 750-5XX / 8DO     BitOffsetOut:0;         BitSizeOut:8;   BitOffsetIn:0;  BitSizeIn:0;    Channels:0;     PiFormat:0;
   Pos:2:  Type: 750-4XX / 8DI     BitOffsetOut:0;         BitSizeOut:0;   BitOffsetIn:0;  BitSizeIn:8;    Channels:0;     PiFormat:0;
  Set Priority: 60 successfully
  -->Init
  Modbus Debug enabled
  Watchdog Init
  Modbus config Init
  Modbus Config MAC Init
  Modbus KBUS Info Init
  Modbus const Init
  Modbus ShortDesctiption Init
  Modbus-Init complete - Ready for take off
  --> RUN
  --> Application in RUN mode
  KBUS set to application state: 1
  New Modbus connection from 192.168.1.85:8665 on socket 14
  Watchdog trigger
  Function :2
  Illegal data address 1 in read_input_bits
  Watchdog trigger
  Function :2
  Illegal data address 1 in read_input_bits
  Watchdog trigger
  Function :2
  Illegal data address 1 in read_input_bits
  Watchdog trigger
  Function :2
  Illegal data address 1 in read_input_bits
  Watchdog trigger
  Function :2
  Illegal data address 1 in read_input_bits
  Watchdog trigger
  Function :2
  Illegal data address 1 in read_input_bits

**Comment by Thomas-Brandt** [comment]
Hi Quentin,

finally there is a new Version 1.5.1 which will fix this issue. Please check.
